### ISSUE TITLE
New Interactive Map

### ISSUE THREAD

**Issue by amandaharlin** [techlahoma/thunderplains-2015#17]
Devin's been working on a [really nice mapbox map](https://a.tiles.mapbox.com/v4/dclark.mna459o6/page.html?access_token=pk.eyJ1IjoiZGNsYXJrIiwiYSI6IkNYd01vRzgifQ.EBgXM0JReblZJXJkgcgiEA#17/35.46645/-97.51584)! 

Devin, thank you for working on this, it really means a lot. If you don't finish, no big deal, but if you do we'd be super grateful. 

The recommendation data is coming from: https://trello.com/b/7rGl7m7o/things-guests-can-do-in-town. 

After a day of work Devin's gotten it to here: 
![2015-07-14 at 11 55 am](https://cloud.githubusercontent.com/assets/716644/8687060/e96b27ee-2a51-11e5-9107-aee4884e64b3.png)

**Comment by vlucas** [comment]
Wow @DevinClark that map is awesome. Thanks for the improvements! :+1:

**Comment by DevinClark** [comment]
I will try to work on getting a PR up this weekend. I really just need to add in more data.

**Comment by the-simian** [comment]
yep, huge improvement over my hexo tag , this is awesome man.
