### ISSUE TITLE
background for speakers? thoughts?

### ISSUE THREAD

**Issue by amandaharlin** [techlahoma/thunderplains-2015#21]
just curious if anyone has any strong feelings about making a backdrop for the speakers (like what fluent conf has done). so the people watching online would see a branded background rather than the conference room.

i'll try and look up pricing and details.

but, so far, any thoughts? good idea if we pull it off for a reasonable price? or maybe this issue doesn't really matter enough to execute a plan for it?

**Comment by the-simian** [comment]
I'd like to see something like this. More physical branding/material day-of looks nice.

**Comment by the-simian** [comment]
same as podium decal- no time/budget. No big deal.
