### ISSUE TITLE
student ticket prices

### ISSUE THREAD

**Issue by DevinClark** [techlahoma/thunderplains-2015#36]
We should add those. Jesse.

**Comment by the-simian** [comment]
Ah yep!

**Comment by amandaharlin** [comment]
@vlucas are we going with lightning ticket prices? i can add in a code on ti.ti too. your call on this though.

**Comment by vlucas** [comment]
Yeah, we can add some student tickets. It's a good idea. We will need to be careful with these as we go forward (read: as our prices increase over time) and be sure to check student ID badges when people pick up their name badges on the conference day itself. For students, we can go with the same price as the lightning tickets.

**Comment by the-simian** [comment]
this is done
