### ISSUE TITLE
Add sponsors to site (edit this list as you need to)

### ISSUE THREAD

**Issue by the-simian** [techlahoma/thunderplains-2015#39]
- [X] Quail Creek
- [X] Simple 
- [x] Digital Ocean

"DigitalOcean is the world’s fastest growing cloud hosting provider built for developers. Our mission is simple: we’re passionate about making complex infrastructure simple and delighting our customers with a seamless experience that brings them joy. New users can easily deploy a blazing fast cloud server in 55 seconds with an intuitive control panel interface, which can be replicated on a larger scale with the company’s straightforward API."

[https://www.digitalocean.com/company/logos-and-badges/](https://www.digitalocean.com/company/logos-and-badges/)

**Comment by the-simian** [comment]
ok this is caught up, closing

**Comment by vlucas** [comment]
Awesome. Great work! :clap:
