### ISSUE TITLE
add the following sponsors to the site

### ISSUE THREAD

**Issue by the-simian** [techlahoma/thunderplains-2015#44]
Oil Law Records   (custom/bronze)
Quail Creek Bank  (silver)
Simple   (t-shirt sponsorship)
WDT, Inc. (bronze)

**Comment by DevinClark** [comment]
This looks done to me.

**Comment by the-simian** [comment]
thanks, yeah @vlucas hit this not long ago

**Comment by vlucas** [comment]
We have another round of sponsors I have to add as well :)
