### ISSUE TITLE
add local childcare centers to website

### ISSUE THREAD

**Issue by carmalou** [techlahoma/thunderplains-2015#48]
Amanda asked me to open an issue with childcare locations...here they are.

Playstreet Hourly Childcare
1623 S. Service Road Moore 73160
405-703-4244

Acorn Children's Center
3601 NW 51st St OKC 73112
405-946-3223

Children's Lighthouse
540 N. Council OKC 73127
405-789-0661

Children's Lighthouse
5816 NW 36th St OKC 73122
405-947-4002

Children's Lighthouse
6624 NW 63rd St OKC 73132
405-721-1830

"Here is a list of local childcare centers that allow for hourly or daily care. Please call them in advance to arrange for this type of care, as most centers are only able to accept drop-ins based on availability."

**Comment by the-simian** [comment]
Thanks for this list! We'll need to update the site with a resources area to put a lot of this, and some other things.

**Comment by amandaharlin** [comment]
Glad you compiled the list. Added childcare to the ticket confirmation form
in the scholarship emails sent out this morning!
