### ISSUE TITLE
Update the Mozilla icon to  use the FDE wordmark

### ISSUE THREAD

**Issue by the-simian** [techlahoma/thunderplains-2015#51]
the icons are here: https://www.mozilla.org/en-US/styleguide/identity/firefox/wordmarks/#firefox-developer

**Comment by the-simian** [comment]
![image](https://cloud.githubusercontent.com/assets/954596/10435543/496447f4-70e6-11e5-96ac-ccc0bc6be58b.png)

**Comment by the-simian** [comment]
Had to use the jpeg cause the png, with white text wasn't legible

**Comment by amandaharlin** [comment]
Great job on this
