### ISSUE TITLE
Speaker Dinner Reservations

### ISSUE THREAD

**Issue by vlucas** [techlahoma/thunderplains-2015#62]
We have the full-court room at Kevin Durant's in Bricktown reserved. We plan to have around 25 people for the dinner.

**Comment by the-simian** [comment]
This is the menu for the private room:
[Kd's Private Dining.pdf](https://github.com/techlahoma/thunderplains-2015/files/15094/Kd.s.Private.Dining.pdf)

**Comment by the-simian** [comment]
Dining Layout

![image](https://cloud.githubusercontent.com/assets/954596/10550521/0b08a02a-740d-11e5-87e4-31127ed28a6a.png)

**Comment by vlucas** [comment]
KD's private dining is _NOT_ the room we are getting. There is a separate "full court" room that is more cost effective for us.

**Comment by the-simian** [comment]
Ah thanks vance, is the menu the same? I updated the image

**Comment by vlucas** [comment]
Yes - the menu is the same.
