### ISSUE TITLE
Add Iheanyi Ekechukwu to speaker list

### ISSUE THREAD

**Issue by amandaharlin** [techlahoma/thunderplains-2015#63]
Yay!!! omg thank you Iheanyi for speaking, Jesse for confirming a speaker asap and lawnsea for helping.

**Comment by the-simian** [comment]
Ok I have the basic talk description and bio up, I'll have @iheanyi review it, and we can make updates before I close

**Comment by the-simian** [comment]
ok I need to add a link to the bio, then I can close

**Comment by iheanyi** [comment]
No problem y'all. =)

**Comment by the-simian** [comment]
all done!
