### ISSUE TITLE
Update New Spin's logo 

### ISSUE THREAD

**Issue by amandaharlin** [techlahoma/thunderplains-2015#64]
.eps asset is in email thread, just wanted to put the screencap of it in here so we'd all be on the same page
<img width="584" alt="screen shot 2015-10-26 at 4 30 42 pm" src="https://cloud.githubusercontent.com/assets/716644/10743101/fe81573a-7bfe-11e5-94ca-f7d6d3cabf25.png">

**Comment by the-simian** [comment]
thank you, this helps me keep on this

**Comment by amandaharlin** [comment]
oh no, thank _you_ <3 :sparkles:
